#!/usr/bin/env python
#!/bin/bash

import subprocess
import toml

config = toml.load('/etc/kiosk.toml').get('wifi', None)

if config:
    #nmcli d connect wlp1s0

    cmd = [
        "/usr/bin/nmcli", "d", "wifi", "connect",
        config['ssid'],
        "password", config['passphrase'],
        "ifname", config["ifname"]
    ]


    subprocess.check_call(cmd, stdin=None, stderr=None, stdout=subprocess.PIPE)
